# Generated by Django 4.2 on 2023-04-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
    ]
