# Generated by Django 4.2 on 2023-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_rename_price_house_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="pets_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
